### ISSUE TITLE
zshの補完ファイルで悩む

### ISSUE THREAD

**Issue by sasairc** [sasairc/clangsay#1]
Makefileの21行目に定義されているCOWPATHを、`make`時に置き換えるようにし、
`make install`した時に、_clangsayも一括でインストールしたい。  
### 悩み
- `$fpath`が、zshのインストール方法によって左右される
  A. aptから入れれば/usr/share/zsh/site-function
  B. tar玉等から入れれば/usr/local/share/zsh/site-function
- そもそも、zshを使っている人が少ない（bashとzshの補完関数には互換性が無い）

**Comment by 844196** [comment]
> $fpathが、zshのインストール方法によって左右される
> A. aptから入れれば/usr/share/zsh/site-function
> B. tar玉等から入れれば/usr/local/share/zsh/site-function

具体的にどれだったかは忘れましたが、インストールはされず「`misc`に補完が入ってるから適時コピーして使ってね」みたいなツールはありました。

同時にインストールするのであれば、ディレクトリを存在確認か`$fpath`を見て、って感じですかね...

**Comment by sasairc** [comment]
@844196 
回答ありがとナス！

> 具体的にどれだったかは忘れましたが、インストールはされず「miscに補完が入ってるから適時コピーして使ってね」みたいなツールはありました。

`make`時に置き換えのみして、コピーは手動でするのが一番良さそうですね・・・
試しに作ってみます

**Comment by mollifier** [comment]
bashとzshの補完ファイルを含んでいるプロジェクトの例として、Gitがありますね。Gitのソースはチラッとしか見ていませんが、
1. bash用の補完ファイル
2. zsh用の補完ファイル

の2つが用意されています。そして、大部分の処理は1.に書いて、2.から1を読み込む、というふうにして共通化しているようです(1.はzshから読み込んでも動作するように書く)。 

あとは、make installのときに1.も一緒にインストールして、2.は「ユーザ側で手動で好きなところに置いてね」という方針みたいです。

これを真似するのはけっこう大変だと思いますが、参考までに紹介しました。

**Comment by sasairc** [comment]
@mollifier 
ありがとうございます！早速探してみました。
completion.bashの中でも環境変数をチェックして、bashとzsh両方で読めるようにしてあるんですね。
参考にさせて頂きます。

**Comment by sasairc** [comment]
23382a0950
修正
