### ISSUE TITLE
milk.cowのファイル名変更について

### ISSUE THREAD

**Issue by sasairc** [sasairc/clangsay#12]
`cowsay`と`COWPATH`を共有した際に、`cowsay`側の`milk.cow`と衝突してしまうので、ファイル名の変更を考えています。
一個人としては`zen-noh-milk.cow`を検討していますが、何か良いファイル名があれば提案して頂ければ嬉しいです。
![n1000](https://cloud.githubusercontent.com/assets/9349287/8312746/7ee74ed6-1a19-11e5-9746-08ba011c7ea6.gif)

**Comment by 844196** [comment]
![](http://keshimani.com/pipipiga/img/Novelty/n001_1.jpg)

`gyunyu-kesigomu.cow`とかいろいろ考えたんですが、特に思い浮かばないので`zen-noh-milk.cow`で

**Comment by sasairc** [comment]
@844196 
:eggplant: 
これから変更します

**Comment by sasairc** [comment]
- 変更
  72bf817
  50889ae

このIssueを閉じます。
