### ISSUE TITLE
stdinにデータが無い場合、その時点でプログラムを終了させるべきか否か

### ISSUE THREAD

**Issue by sasairc** [sasairc/clangsay#18]
#### 問題？

パイプの読み込み先として、存在しないコマンドの標準出力を指定した場合、現状では

``` shellsession
% a | clangsay
zsh: command not found: a
 _-
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

という結果になり、加えてファイルにリダイレクトさせた場合は

``` shellsession
% a | clangsay > test.txt
zsh: command not found: a
% cat test.txt
 _-
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

という具合に「言葉を失った可哀想な牛さん」のみ書き込みされてしまいます。

私自身、この振る舞いを以前から把握しており、本家`cowsay`も同じ振る舞いをすることに加えて、
特に不都合（バグではない訳だし、この振る舞いは好き）が無かったので放置をしていました。

これはあくまで一個人での判断ですので、もし不都合があれば「`stdin`にデータが無い場合、その時点でプログラムを終了させる」よう修正したいと思います。
「別にこのままで良いよ」という場合は、現状の状態を維持しますので、何かしら意見を書いて頂ければ嬉しいです。

![default](https://cloud.githubusercontent.com/assets/9349287/8505311/848708e8-221d-11e5-9b92-f7d986220120.png)

**Comment by 844196** [comment]
今のマ゜ッ！マ゜ッ！でもいいような気がする（けど`_-`が気になる。吹き出し部分の最小構成かな？）

**Comment by sasairc** [comment]
@844196 
じゃあ今のンンッ… マ゜ッ！ア゛ッ！↑にしておきます。
吹き出し部分に関しては、`stdin`にデータが無いと、文字を格納する配列長が`0`（厳密には二次元配列の`x, y`共に`0`）なので、そのような表示になってしまうのです。

**Comment by sasairc** [comment]
とりあえず、暫くの間は本Issueを開きっぱなしにしておきます。

**Comment by sasairc** [comment]
あーすでに一回この話が閉じろ
