### ISSUE TITLE
末尾にEOCがないcowfileを指定し実行した際の挙動について

### ISSUE THREAD

**Issue by 844196** [sasairc/clangsay#23]
判断つかないので起票

末尾に`EOC`がないcowfileを指定し実行した際、`cowsay`の場合は「`EOC`が見つからない」としてエラーになるが、

``` shellsession
$ renge | cowsay -f ./cows/respawn.cow
cowsay: Can't find string terminator "EOC" anywhere before EOF at cows/respawn.cow line 1, <STDIN> line 1.
```

`clangsay`では特にエラーもなく正常終了する。

``` shellsession
$ renge | clangsay -f ./cows/respawn.cow
略
```

これは期待される正しい挙動でしょうか？

---

今のところ末尾に`EOC`のないお行儀の悪いcowfileは`respawn.cow`のみなので、確認が取れ次第修正プルリクエストを送ります...

**Comment by sasairc** [comment]
@844196 

> 末尾にEOCがないcowfileを指定し実行した際、cowsayの場合は「EOCが見つからない」としてエラーになるが
> これは期待される正しい挙動でしょうか？

出力は`subset.c`の`print_cow()`が担っていますが、それは正常な動作です。
clangsayの場合、予めcowfileのデータを全てバッファに貯め、行数をカウントした上で出力関数に渡しています。
ですので「末尾の`EOC`は`stdout`への出力を終了する合図」でしかないので、それが無い場合は行末まで出力してしまします。

``` c
for (i = 0; i < lines; i++) {   /* 全行に対してループを回す */

    中略

    /* 現在の行の文字列内に、先頭のEOC（開始合図）が存在するか */
    if (strstr(str[i], "EOC")) {    
        block = true;           /* 出力ブロックをtrueに */
        continue;

    /* 現在の行の文字列内に、末尾のEOC（終了合図）が存在するか */
    } else if (strstr(str[i], "EOC") && block == true) {    
        block = false;          /* 出力ブロックをfalseに */

    /* ブロック内であれば現在の行の文字列を出力 */
    } if (block == true) {
        fprintf(stdout, "%s\n", str[i]);
    }
}
```

---

ただお行儀の悪いcowfileである事には変わらないですね・・・（あくまでcowsay互換でありたいので）

**Comment by 844196** [comment]
@sasairc 
確認しました。これから1行プルリクエストを送るのでおねがいします。
