### ISSUE TITLE
cowファイルの提供について

### ISSUE THREAD

**Issue by 844196** [sasairc/clangsay#5]
初Issueです

現在メンテしてる[844196/RengeSay](https://github.com/844196/RengeSay) ですが、機能自体は`renge.cow`の同梱と`cowsay`のエイリアスなので、高機能版の`clangsay`に統合していただければそれはとっても嬉しいなって（MDK）

その他、`charlie.cow`も提供したく思います。同意が得られたらPRを切ります。
## `charlie.cow`

![2015-03-15_17-38-55 png](https://cloud.githubusercontent.com/assets/4990822/6655240/2a4bb930-cb3a-11e4-8e80-256e45598901.png)

---

![bxbza14cyaalsuc png-large](https://cloud.githubusercontent.com/assets/4990822/6655244/81d7976e-cb3a-11e4-9b6a-a9038f8ab453.png)

**Comment by sasairc** [comment]
@844196 
あ、いいっすよ（快諾）
送ってくれ次第、直ちにマージします。
![default](https://cloud.githubusercontent.com/assets/9349287/6656184/78907fa8-cb63-11e4-967d-61d20bfa9731.png)

**Comment by 844196** [comment]
:eggplant:

**Comment by 844196** [comment]
@sasairc 

マージ確認しました、ありがとうございます。
本Issueを閉じます。
