### ISSUE TITLE
AAのみのcowfileと、ANSIエスケープ文字を用いたドット絵cowfileを分ける

### ISSUE THREAD

**Issue by sasairc** [sasairc/clangsay#59]
![ss](https://cloud.githubusercontent.com/assets/9349287/10552022/ef0ed914-748b-11e5-8d43-2c6a2dc9892d.png)
## 問題
- ドット絵cowfileは比較的大型になる傾向がある  
  崩れるのはかなしい（かなしい）
- 素のttyで利用する際の問題  
  フレームバッファとして`vesafb`や`uvesafb`を利用した場合、256色表示ができない。  
  ※ `KMS`を利用した場合の挙動は未把握
## 解決案

ソースツリーを`cows/asciiart`と`cows/pixelart`に分けた後、
1. `make install-cows-asciiart`でアスキーアートなcowfileをインストール
2. `make install-cows-pixelart`でドット絵なcowfileをインストール
3. `make install-cows`で従来通り、全cowfileをインストール

上記のよう修正し、インストール時の柔軟性を高めたい。

**Comment by 844196** [comment]
:oden: 

![2015-10-17_06-44-00](https://cloud.githubusercontent.com/assets/4990822/10554029/81e9dbb8-749a-11e5-93f0-29410ab0e881.png)

**Comment by sasairc** [comment]
@844196 
![1360242920152](https://cloud.githubusercontent.com/assets/9349287/10554177/3ef00c9a-749c-11e5-82f1-25ac7091b9d5.jpg)

**Comment by sasairc** [comment]
#60 へ移動
