### ISSUE TITLE
Collaborators権限に関するガイドライン

### ISSUE THREAD

**Issue by sasairc** [sasairc/clangsay#74]
_[「貴方の作ったcowfileを求む！」](https://www.youtube.com/watch?v=_1uu1e42oZE)_

今までに素敵なcowfileを作成して頂いた方（複数形ではない）へ、Collaborators権限を追加しました。
以上の権限を持つ方は、PRで私の認可を得ることなく、自由に追加や変更を行うことができます。
1. ネタは問いません。なんでもござれ。
2. cowfileを追加または変更した後、`master`ブランチへ`push`して下さい。
3. `AUTHORS`へ作成したファイル名を含むクレジットを記述して下さい。
4. `master`ブランチ宛であれば、別途作業ブランチを作成して頂いて構いません。
5. :ramen: 
## 

基本的に、ソースコードの修正は`w_0.0.0`のような「次期バージョン名」ブランチ上で行っているので、`master`へ変更があれば、本ブランチへマージします。
また、`./cows`及び`AUTHORS`以外のファイルの編集に関しては、事前にtwitterやissueでご一報下さい。

**Comment by 844196** [comment]
![2016-03-08_18-25-17](https://cloud.githubusercontent.com/assets/4990822/13597300/2abe60ac-e55b-11e5-985d-5e8b8187eadd.png)

**Comment by sasairc** [comment]
![default](https://cloud.githubusercontent.com/assets/9349287/13605252/ea1b0d32-e589-11e5-921f-2f2f21384a45.png)
