### ISSUE TITLE
ANSIエスケープシーケンスを考慮して欲しい

### ISSUE THREAD

**Issue by 844196** [sasairc/clangsay#79]
![shell 2016-09-18 21-58-32](https://cloud.githubusercontent.com/assets/4990822/18615821/37e5d534-7deb-11e6-9d60-7b3c7daf7bc3.png)

色付き文字をclangsayに通すと吹き出しの長さがANSIエスケープシーケンスもカウントされるため、吹き出しが長くなってしまいます。
吹き出しの長さはANSIエスケープシーケンスを除いた文字数で算出してほしいです。

**Comment by sasairc** [comment]
@844196 
承知しました。あと、Homebrewの件ありがとうございます。
ANSIエスケープシーケンスの検出となると、POSIX標準の`regex.h`で対応しようかと。
早速弄ってみます。

**Comment by 844196** [comment]
@sasairc 🙇

**Comment by sasairc** [comment]
@844196 
対応させてみました。調子を見て問題がなければ1.6.3で導入&本issueをクローズします。

**Comment by 844196** [comment]
@sasairc いい感じです、ありがとうございます！

![shell 2016-09-19 00-54-47](https://cloud.githubusercontent.com/assets/4990822/18617132/b3ec5906-7e03-11e6-8681-7b6dc91a506e.png)
