### ISSUE TITLE
READMEの画像が404で表示されない

### ISSUE THREAD

**Issue by 844196** [sasairc/clangsay#92]
こっちからキャッシュの破棄を送ってみましたがダメでした。

良さげなイメージ待ってます

**Comment by sasairc** [comment]
@844196 
あら、画像が表示されていない・・・直しておきます

**Comment by sasairc** [comment]
@844196 
:eggplant: 
![tumblr_ooo4nkihxj1t21tblo1_500](https://user-images.githubusercontent.com/9349287/28264157-a13bfd34-6b24-11e7-8449-0bda1f238999.gif)
